services:
  n64-c-builder:
    build:
      context: .
      dockerfile: Dockerfile
    command: make -f GNUmakefile HOST_SWIFT=1 SWIFTC_HOST="/swift-host/bin/swiftc"
    platform: linux/amd64
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
      - /Volumes/Crucial-2TB/Developer/build/Ninja-ReleaseAssert/swift-macosx-arm64:/swift-host:ro
    environment:
      - HOST_SWIFT=1
      - SWIFTC_HOST=/swift-host/bin/swiftc
      - SWIFT_LIBS=/workspace/swift-libs/mipsel-none-none-elf